name: Check Quiche release

on: 
  workflow_dispatch:

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Quiche Release
        shell: bash
        run: |
          set -x
          gh release list --repo cloudflare/quiche -L 1
